### ISSUE TITLE
Date when going selecting negative UTC

### ISSUE THREAD

**Issue by potibm** [creativenucleus/jtruk-timezoner.js#1]
Hello @creativenucleus,

when you take https://outlinedemoparty.nl/timetable/, select "UTC-12", shouldn't the entry

- 20:00 (UTC-12) (on Sat) FOOD Breakfast + dj set Roeltje

actually be

- 20:00 (UTC-12) (on Thu) FOOD Breakfast + dj set Roeltje

The same problem occurred while adding your script (really great idea btw!) to the Evoke website. Best regards

Poti

**Comment by creativenucleus** [comment]
Thank you. Good find!

This should be fixed in latest =)
